const companion=document.querySelector('.serena-companion'),character=document.querySelector('.companion-character'),menu=document.querySelector('.companion-menu'),restore=document.querySelector('.companion-restore');let drag=null,moved=false;
function positionMenu(){const r=companion.getBoundingClientRect();const width=menu.offsetWidth||270,height=menu.offsetHeight||230;menu.style.left=Math.max(12,Math.min(innerWidth-width-12,r.right-width))+'px';menu.style.top=Math.max(12,Math.min(innerHeight-height-12,r.top-height-12))+'px'}
function greetCompanion(){menu.hidden=!menu.hidden;if(!menu.hidden)positionMenu();character.classList.remove('waving');void character.offsetWidth;character.classList.add('waving');setTimeout(()=>character.classList.remove('waving'),1800);document.querySelector('.companion-hint').hidden=true}
character.addEventListener('pointerdown',e=>{if(e.button!==0)return;const r=companion.getBoundingClientRect();drag={x:e.clientX,y:e.clientY,left:r.left,top:r.top};moved=false;character.setPointerCapture(e.pointerId)});
character.addEventListener('pointermove',e=>{if(!drag)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(Math.hypot(dx,dy)>6)moved=true;if(!moved)return;companion.classList.add('dragging');companion.style.right='auto';companion.style.bottom='auto';companion.style.left=Math.max(0,Math.min(innerWidth-companion.offsetWidth,drag.left+dx))+'px';companion.style.top=Math.max(0,Math.min(innerHeight-companion.offsetHeight,drag.top+dy))+'px';if(!menu.hidden)positionMenu()});
character.addEventListener('pointerup',()=>{if(drag&&!moved)greetCompanion();drag=null;companion.classList.remove('dragging')});character.addEventListener('pointercancel',()=>{drag=null;companion.classList.remove('dragging')});character.addEventListener('click',e=>{if(e.detail===0)greetCompanion()});
document.querySelector('.companion-close').addEventListener('click',()=>{menu.hidden=true;character.focus()});document.querySelector('.companion-hide').addEventListener('click',()=>{menu.hidden=true;companion.hidden=true;restore.hidden=false;restore.focus()});restore.addEventListener('click',()=>{companion.hidden=false;restore.hidden=true;character.focus()});
document.querySelector('.companion-jump').addEventListener('click',()=>{character.classList.remove('bounce');void character.offsetWidth;character.classList.add('bounce');document.querySelector('.companion-message').textContent='收到！送你一个元气小跳跃。'});
menu.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>menu.hidden=true));addEventListener('keydown',e=>{if(e.key==='Escape'&&!menu.hidden){menu.hidden=true;character.focus()}});addEventListener('resize',()=>{const r=companion.getBoundingClientRect();if(r.right>innerWidth||r.bottom>innerHeight){companion.style.left='auto';companion.style.top='auto';companion.style.right='18px';companion.style.bottom='90px'}if(!menu.hidden)positionMenu()});
