(()=>{
const cards=[...document.querySelectorAll('.work-card')];let saved=[];try{saved=JSON.parse(localStorage.getItem('serena-saved')||'[]');if(!Array.isArray(saved))saved=[]}catch{}
const savedFilter=document.querySelector('.saved-filter');let onlySaved=false;
function persist(){try{localStorage.setItem('serena-saved',JSON.stringify(saved))}catch{}}
function renderSaved(){document.querySelector('.saved-count').textContent=saved.length;cards.forEach((card,i)=>{const button=card.querySelector('.save-work');const active=saved.includes(i);button.setAttribute('aria-pressed',String(active));button.textContent=active?'♥ 已收藏':'♡ 收藏作品';if(onlySaved)card.hidden=!active});savedFilter.setAttribute('aria-pressed',String(onlySaved));document.querySelector('.saved-empty').hidden=!onlySaved||saved.length>0;}
cards.forEach((card,i)=>{const button=document.createElement('button');button.className='save-work';button.addEventListener('click',()=>{saved=saved.includes(i)?saved.filter(x=>x!==i):[...saved,i];persist();renderSaved()});card.append(button)});
const empty=document.createElement('p');empty.className='saved-empty';empty.textContent='还没有收藏，点作品上的爱心试试';document.querySelector('.work-grid').after(empty);
savedFilter.addEventListener('click',()=>{onlySaved=!onlySaved;document.querySelectorAll('[data-filter]').forEach(b=>b.setAttribute('aria-pressed',String(!onlySaved&&b.dataset.filter==='all')));cards.forEach(c=>{c.hidden=false;c.classList.add('visible')});renderSaved()});document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{onlySaved=false;savedFilter.setAttribute('aria-pressed','false');empty.hidden=true}));renderSaved();
const paths={writing:{target:'.work-card.script',text:'从《郝顺求职记》开始，看看我如何把观察转化为故事'},operations:{target:'.timeline article:nth-child(2)',text:'看看我的运营成果：月流水增长、连续 TOP 3，以及团队流程优化'},venture:{target:'#venture',text:'走进 Repair Mate，探索我如何把 AI 想法推进到创业提案与原型'}};
function visit(key){const route=paths[key];document.querySelector('.explore-answer').textContent=route.text;document.querySelectorAll('[data-path]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.path===key)));onlySaved=false;document.querySelector('[data-filter="all"]').click();const target=document.querySelector(route.target);target.classList.add('visible','explore-focus');target.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'auto':'smooth',block:'center'});setTimeout(()=>target.classList.remove('explore-focus'),2400)}
document.querySelectorAll('[data-path]').forEach(b=>b.addEventListener('click',()=>visit(b.dataset.path)));
const character=document.querySelector('.companion-character');document.querySelector('.companion-wave').addEventListener('click',()=>{character.classList.remove('waving');void character.offsetWidth;character.classList.add('waving');document.querySelector('.companion-message').textContent='嗨！今天也很高兴见到你';setTimeout(()=>character.classList.remove('waving'),1800)});document.querySelector('.companion-surprise').addEventListener('click',()=>{document.querySelector('.companion-menu').hidden=true;const keys=Object.keys(paths);visit(keys[Math.floor(Math.random()*keys.length)])});
})();

(()=>{const character=document.querySelector('.companion-character');const reduce=matchMedia('(prefers-reduced-motion:reduce)');let frame=0;addEventListener('pointermove',event=>{if(event.pointerType==='touch'||reduce.matches||document.body.classList.contains('motion-paused')||document.querySelector('.serena-companion').classList.contains('dragging'))return;if(frame)return;frame=requestAnimationFrame(()=>{frame=0;const r=character.getBoundingClientRect();const dx=Math.max(-1,Math.min(1,(event.clientX-r.left-r.width/2)/350));const dy=Math.max(-1,Math.min(1,(event.clientY-r.top-r.height/2)/350));character.style.setProperty('--look-x',dx*7+'deg');character.style.setProperty('--look-y',-dy*3+'deg')})},{passive:true});document.querySelector('.companion-wave').addEventListener('click',()=>{if(reduce.matches||document.body.classList.contains('motion-paused'))return;const spark=document.createElement('span');spark.className='hello-spark';spark.textContent='✦';character.append(spark);setTimeout(()=>spark.remove(),1000)});})();
