const reader=document.querySelector('#reader');let writing;
const definitions={script:{title:'《郝顺求职记》 · 戏剧剧本',slides:[3,4,5,6,7]},review:{title:'《活着》 · 文学评论节选',slides:[11,12]}};
document.querySelectorAll('[data-work]').forEach(button=>button.addEventListener('click',async()=>{const def=definitions[button.dataset.work];document.querySelector('#reader-title').textContent=def.title;document.querySelector('#reader-content').textContent='正在加载作品…';reader.showModal();try{if(!writing){const response=await fetch('assets/writing.json');if(!response.ok)throw Error();writing=await response.json()}document.querySelector('#reader-content').textContent=def.slides.map(x=>writing[x]).join('\n\n────────────\n\n')}catch{document.querySelector('#reader-content').textContent='暂时无法读取作品，请关闭窗口后重试。'}}));document.querySelector('#close-reader').addEventListener('click',()=>reader.close());reader.addEventListener('click',e=>{if(e.target===reader){const r=reader.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)reader.close()}});
const reducedMotion=matchMedia('(prefers-reduced-motion: reduce)');
const toggle=document.querySelector('.motion-toggle');let paused=reducedMotion.matches;
function updateMotion(){document.body.classList.toggle('motion-paused',paused);toggle.textContent=paused?'播放动效':'暂停动效';toggle.setAttribute('aria-pressed',String(paused));const video=document.querySelector('.hero-image video');if(video){if(paused)video.pause();else video.play().catch(()=>{})}}
toggle.addEventListener('click',()=>{paused=!paused;updateMotion()});updateMotion();
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.08});
document.querySelectorAll('.section-heading,.about-content,.timeline article,.works-heading,.work-card,.performance,.extras>div,.contact h2').forEach(el=>{el.classList.add('reveal');observer.observe(el)});
const progress=document.querySelector('.scroll-progress');function updateProgress(){const height=document.documentElement.scrollHeight-innerHeight;progress.style.width=`${height>0?scrollY/height*100:0}%`}addEventListener('scroll',updateProgress,{passive:true});updateProgress();
const hero=document.querySelector('.hero'),portrait=document.querySelector('.hero-image');hero.addEventListener('pointermove',event=>{if(paused||event.pointerType==='touch')return;const r=hero.getBoundingClientRect();const x=(event.clientX-r.left)/r.width-.5,y=(event.clientY-r.top)/r.height-.5;portrait.style.transform=`perspective(1200px) translate(${x*18}px,${y*14}px) rotateY(${x*7}deg) rotateX(${y*-4}deg) scale(1.035)`});hero.addEventListener('pointerleave',()=>{portrait.style.transform=''});
document.querySelectorAll('.work-card').forEach(card=>{card.addEventListener('pointermove',e=>{if(paused||e.pointerType==='touch')return;const r=card.getBoundingClientRect();card.style.transform=`perspective(1000px) rotateX(${((e.clientY-r.top)/r.height-.5)*-4}deg) rotateY(${((e.clientX-r.left)/r.width-.5)*5}deg)`});card.addEventListener('pointerleave',()=>{card.style.transform=''})});
const panel=document.querySelector('#gini-panel');const greet=document.querySelector('.avatar-hit');
greet.addEventListener('click',()=>{panel.hidden=false;portrait.classList.remove('avatar-greet');void portrait.offsetWidth;portrait.classList.add('avatar-greet');panel.querySelector('.panel-close').focus()});
function closePanel(){panel.hidden=true;greet.focus()}
panel.querySelector('.panel-close').addEventListener('click',closePanel);document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!panel.hidden)closePanel()});
const giniFacts={writing:{text:'我在香港都会大学修读创意写作，创作过心理剧《郝顺求职记》。对我来说，文字能把难以说出口的感受留下来。',link:'#works',label:'读我的作品'},work:{text:'我曾参与湖北日报全媒体集团新闻采编和“在线访谈”制作，也做过直播内容与团队运营。策划之后把事情执行到位，是我工作中很重视的一部分。',link:'#experience',label:'看看我的工作经历'},stage:{text:'我毕业于云南艺术学院表演专业，在《宝岛一村》中饰演钱老奶奶，也参与剧目海报设计。',link:'#works',label:'看看舞台与作品'}};
panel.querySelectorAll('[data-gini]').forEach(button=>button.addEventListener('click',()=>{const fact=giniFacts[button.dataset.gini];document.querySelector('#gini-answer').textContent=fact.text;const explore=document.querySelector('#gini-explore');explore.href=fact.link;explore.textContent=fact.label;panel.querySelectorAll('[data-gini]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)))}));document.querySelector('#gini-explore').addEventListener('click',()=>panel.hidden=true);
document.querySelectorAll('[data-filter]').forEach(button=>button.addEventListener('click',()=>{let count=0;document.querySelectorAll('.work-card').forEach(card=>{card.hidden=button.dataset.filter!=='all'&&card.dataset.category!==button.dataset.filter;if(!card.hidden){count++;card.classList.add('visible')}});document.querySelectorAll('[data-filter]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));document.querySelector('#filter-status').textContent=`显示 ${count} 件作品`;}));
const chapterLinks=[...document.querySelectorAll('[data-section]')];function updateChapter(){let selected=null;chapterLinks.forEach(link=>{const section=document.getElementById(link.dataset.section);if(section.getBoundingClientRect().top<innerHeight*.45)selected=link});chapterLinks.forEach(link=>{if(link===selected)link.setAttribute('aria-current','true');else link.removeAttribute('aria-current')})}addEventListener('scroll',updateChapter,{passive:true});updateChapter();
let toastTimer;document.querySelector('.copy-email').addEventListener('click',async()=>{const email='serenagini02@gmail.com',toast=document.querySelector('.toast');try{await navigator.clipboard.writeText(email);toast.textContent='邮箱已复制'}catch{toast.textContent=`请复制：${email}`}toast.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.hidden=true,3500)});
const certificates={startup:'香港跨校创业培训 · 2026',teaching:'优秀支教教师',volunteer:'公益艺术支教荣誉',workshop:'国际表演大师班结业'};const certificateViewer=document.querySelector('#certificate-viewer');document.querySelectorAll('[data-cert]').forEach(button=>button.addEventListener('click',()=>{const key=button.dataset.cert;document.querySelector('#certificate-title').textContent=certificates[key];const image=document.querySelector('#certificate-image');image.src=`assets/${key}.webp`;image.alt=certificates[key]+'证书扫描件';certificateViewer.showModal()}));document.querySelector('#close-certificate').addEventListener('click',()=>certificateViewer.close());
